language: java

jdk:
  - openjdk8

# https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
before_install:
  - chmod +x gradlew
  - chmod +x mvnw

install: skip

script:
  - ./mvnw cobertura:cobertura -B
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)